### ISSUE TITLE
Dependency conflicts when install Object Detection API and failed of load cuDNN lib on Google Colab 

### ISSUE THREAD

**Issue by kateriska** [tensorflow/models#10359]
## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/object_detection/packages/tf2/setup.py

## 2. Describe the bug

During installation of Object Detection API on Google Colab following message displays:

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.`
`multiprocess 0.70.12.2 requires dill>=0.3.4, but you have dill 0.3.1.1 which is incompatible.`
`google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.26.0 which is incompatible.`
`datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.`

## 3. Steps to reproduce

Steps to reproduce the behavior.

1. Create notebook on Google Colab

2. Clone Tensorflow Models
`!git clone https://github.com/tensorflow/models model`

3. Installation of Object Detection API
`!apt-get install protobuf-compiler`
`!cd model/research && protoc object_detection/protos/*.proto --python_out=. && cp object_detection/packages/tf2/setup.py . && python -m pip install .`

## 4. Expected behavior

Object Detection API should be installed sucessfully. Maybe this dependency conflict is also reason of following error described in Additional context part, because a week ago, my Google Colab notebook with the same commands and same code worked fine without any errors, Object Detection API was installed without any erros and training of model was processed.

## 5. Additional context
Maybe this issue could be origin of also this error during training on Google Colab:
`!python model/research/object_detection/model_main_tf2.py --model_dir=trained_models/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8 --pipeline_config_path=trained_models/ssd_mobilenet_v2_fpnlite_320x320_coco17_tpu-8/pipeline.config --num_train_steps=20000`

`2021-11-10 10:28:09.745468: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2021-11-10 10:28:09.771767: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2021-11-10 10:28:09.772550: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2021-11-10 10:28:09.773828: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.`
`2021-11-10 10:28:09.774101: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2021-11-10 10:28:09.774915: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2021-11-10 10:28:09.775713: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2021-11-10 10:28:10.319459: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2021-11-10 10:28:10.320174: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2021-11-10 10:28:10.320904: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero`
`2021-11-10 10:28:10.321679: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:39] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.`
`2021-11-10 10:28:10.321745: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 10801 MB memory:  -> device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7`
`INFO:tensorflow:Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)
I1110 10:28:10.328551 139781256206208 mirrored_strategy.py:369] Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0',)`
`INFO:tensorflow:Maybe overwriting train_steps: 20000
I1110 10:28:10.332983 139781256206208 config_util.py:552] Maybe overwriting train_steps: 20000`
`INFO:tensorflow:Maybe overwriting use_bfloat16: False`
`I1110 10:28:10.333153 139781256206208 config_util.py:552] Maybe overwriting use_bfloat16: False`
`WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py:558: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.`
`Instructions for updating:
rename to distribute_datasets_from_function`
`W1110 10:28:10.466923 139781256206208 deprecation.py:345] From /usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py:558: StrategyBase.experimental_distribute_datasets_from_function (from tensorflow.python.distribute.distribute_lib) is deprecated and will be removed in a future version.`
`Instructions for updating:
rename to distribute_datasets_from_function`
`INFO:tensorflow:Reading unweighted datasets: ['annotations/train.record']
I1110 10:28:10.471539 139781256206208 dataset_builder.py:163] Reading unweighted datasets: ['annotations/train.record']`
`INFO:tensorflow:Reading record datasets for input file: ['annotations/train.record']`
`I1110 10:28:10.471800 139781256206208 dataset_builder.py:80] Reading record datasets for input file: ['annotations/train.record']`
`INFO:tensorflow:Number of filenames to read: 1`
`I1110 10:28:10.471947 139781256206208 dataset_builder.py:81] Number of filenames to read: 1`
`WARNING:tensorflow:num_readers has been reduced to 1 to match input file shards.`
`W1110 10:28:10.472104 139781256206208 dataset_builder.py:88] num_readers has been reduced to 1 to match input file shards.
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/object_detection/builders/dataset_builder.py:105: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.`
`Instructions for updating:`
`Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.`
`W1110 10:28:10.474788 139781256206208 deprecation.py:345] From /usr/local/lib/python3.7/dist-packages/object_detection/builders/dataset_builder.py:105: parallel_interleave (from tensorflow.python.data.experimental.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:`
`Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_deterministic`.`
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/object_detection/builders/dataset_builder.py:237: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
`Use `tf.data.Dataset.map()`
`W1110 10:28:10.499684 139781256206208 deprecation.py:345] From /usr/local/lib/python3.7/dist-packages/object_detection/builders/dataset_builder.py:237: DatasetV1.map_with_legacy_function (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.`
Instructions for updating:
`Use `tf.data.Dataset.map()`
`WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:206: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:`
`Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.`
`W1110 10:28:18.425311 139781256206208 deprecation.py:345] From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:206: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.`
`Instructions for updating:`
`Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.`
`WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:206: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:`
``seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.`
`W1110 10:28:21.871340 139781256206208 deprecation.py:345] From /usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:206: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.`
`Instructions for updating:`
``seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.`
`WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py:464: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.`
Instructions for updating:
`Use `tf.cast` instead.`
`W1110 10:28:23.739028 139781256206208 deprecation.py:345] From /usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py:464: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.`
`Instructions for updating:`
`Use `tf.cast` instead.`
`2021-11-10 10:28:26.347177: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)`
`/usr/local/lib/python3.7/dist-packages/keras/backend.py:401: UserWarning: `tf.keras.backend.set_learning_phase` is deprecated and will be removed after 2020-10-11. To update it, simply pass a True/False value to the `training` argument of the `__call__` method of your layer or model.`
`  warnings.warn('`tf.keras.backend.set_learning_phase` is deprecated and '`
`2021-11-10 10:28:49.747760: E tensorflow/stream_executor/cuda/cuda_dnn.cc:362] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.`
`2021-11-10 10:28:49.751289: E tensorflow/stream_executor/cuda/cuda_dnn.cc:362] Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.`
`Traceback (most recent call last):`
`  File "model/research/object_detection/model_main_tf2.py", line 115, in <module>`
  `  tf.compat.v1.app.run()`
  `File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)`
`  File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)`
  `File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))`
 ` File "model/research/object_detection/model_main_tf2.py", line 112, in main
    record_summaries=FLAGS.record_summaries)`
`  File "/usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py", line 603, in train_loop
    train_input, unpad_groundtruth_tensors)`
 ` File "/usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py", line 394, in load_fine_tune_checkpoint
    _ensure_model_is_built(model, input_dataset, unpad_groundtruth_tensors)`
  `File "/usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py", line 176, in _ensure_model_is_built
    labels,
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 1286, in run
    return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)`
`  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/distribute_lib.py", line 2849, in call_for_each_replica
    return self._call_for_each_replica(fn, args, kwargs)`
`  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/mirrored_strategy.py", line 671, in _call_for_each_replica
    self._container_strategy(), fn, args, kwargs)`
  `File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/distribute/mirrored_run.py", line 86, in call_for_each_replica
    return wrapped(args, kwargs)`
`  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)`
 ` File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)`
 ` File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 3040, in __call__
    filtered_flat_args, captured_inputs=graph_function.captured_inputs)  # pylint: disable=protected-access`
` File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 1964, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))`
  `File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py", line 596, in call
    ctx=ctx)`
`  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)`
`tensorflow.python.framework.errors_impl.UnknownError:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node ssd_mobile_net_v2fpn_keras_feature_extractor/model/Conv1/Conv2D (defined at /usr/local/lib/python3.7/dist-packages/object_detection/models/ssd_mobilenet_v2_fpn_keras_feature_extractor.py:219) ]] [Op:__inference__dummy_computation_fn_15068]`

`Errors may have originated from an input operation.
Input Source operations connected to node ssd_mobile_net_v2fpn_keras_feature_extractor/model/Conv1/Conv2D:
 args_1 (defined at /usr/local/lib/python3.7/dist-packages/object_detection/model_lib_v2.py:176)`

`Function call stack:
_dummy_computation_fn`

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux - Google Colab
- TensorFlow version (use command below): Actual installed Tensorflow on Google Colab (tensorflow in /usr/local/lib/python3.7/dist-packages (2.7.0))
- Python version: 3.7
- CUDA/cuDNN version: CUDA Version: 11.2
- GPU model and memory: Tesla (GPU on Google Colab)
I hope these errors would be easy to reproduce, because Google Colab is an universal environment.

**Comment by ibyou1997** [comment]
I am facing the same problem.

**Comment by abhilash-chintada** [comment]
This issue seems to be only on GPU, training and inference is working fine on CPU. 
Error says "Loaded runtime CuDNN library: 8.0.5 but source was compiled with: 8.1.0. CuDNN library needs to have matching major version" so I've tried upgrading CuDNN packages to 8.1.* (commands mentioned below) in "cuda", "cuda-11", "cuda-11.1" folders which didn't work. 

!wget https://developer.download.nvidia.com/compute/redist/cudnn/v8.1.0/cudnn-11.2-linux-x64-v8.1.0.77.tgz
!tar -xzvf cudnn-11.2-linux-x64-v8.1.0.77.tgz
!sudo cp cuda/include/cudnn*.h /usr/local/cuda-11/include
!sudo cp cuda/lib64/libcudnn* /usr/local/cuda-11/lib64
!sudo chmod a+r /usr/local/cuda-11/include/cudnn*.h /usr/local/cuda-11/lib64/libcudnn*

**Comment by kabyanil** [comment]
i am facing the exact same issue while trying to train on object detection model on faster r-cnn inception resnet 101 1024x1024.

**Comment by ibyou1997** [comment]
Here is a link to how to solve this [issue.](https://github.com/tensorflow/models/issues/10360#issuecomment-965560460) There an instruction on how you could upgrade CuDNN in google collab

**Comment by alsnac** [comment]
#Just download and install cuDNN 8.1.0:
%%bash
dpkg -i "~/libcudnn8_8.1.1.33-1+cuda11.2_amd64.deb"
ls -l /usr/lib/x86_64-linux-gnu/libcudnn.so.8*

**Comment by kateriska** [comment]
> 

Thank you a lot! This solved my problem ❤️
