### ISSUE TITLE
Unable to install TensorFlow object detection API with Docker

### ISSUE THREAD

**Issue by longqua69** [tensorflow/models#10439]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [x] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [x] I checked to make sure that this issue has not already been filed.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/tree/master/research/...

## 2. Describe the bug

Following the instruction [Object Detection API with TensorFlow 2](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md), I got the error while trying to test the installation via Docker

```
tensorflow@671ab282ccc5:~/models/research$ python object_detection/builders/model_builder_tf2_test.py
Traceback (most recent call last):
  File "object_detection/builders/model_builder_tf2_test.py", line 22, in <module>
    import tensorflow.compat.v1 as tf
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 438, in <module>
    _ll.load_library(_main_dir)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 154, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
```

## 3. Steps to reproduce

Following the guidelines in [Object Detection API with TensorFlow 2](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md), I got the error while trying to test the installation via Docker

```
git clone https://github.com/tensorflow/models.git
cd models
docker build -f research/object_detection/dockerfiles/tf2/Dockerfile -t od .
docker run -it od
python object_detection/builders/model_builder_tf2_test.py
```

## 4. Expected behavior

Install Tensorflow API successfully with Docker

## 5. Additional context

I tried to check whether or not the object detection Docker container can import `tensorflow`

```
tensorflow@671ab282ccc5:~/models/research$ python
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
print(dir(tensorflowTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 438, in <module>
    _ll.load_library(_main_dir)
  File "/home/tensorflow/.local/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 154, in load_library
    py_tf.TF_LoadLibrary(lib)
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
```

## 6. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): WSL2 Windows 10
- Mobile device name if the issue happens on a mobile device: None
- TensorFlow installed from (source or binary): Docker
- TensorFlow version (use command below): 2.7.0
- Python version: 3.6.9
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: 10.1
- GPU model and memory: 
Executing the script `tf_env_collect.sh` returns log file `tf_env.tx`
```
== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system


== cuda libs  ===================================================

== tensorflow installed from info ==================

== python version  ==============================================
(major, minor, micro, releaselevel, serial)

== bazel version  ===============================================
```

**Comment by dmitry-vlt** [comment]
I have the same exact issue on Ubuntu 20.04.1 LTS with CUDA 10.1 (and tried with 11). 
My system config:
-------------------------
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
--------------------------
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.46       Driver Version: 495.46       CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 74%   84C    P0   113W / 180W |   5336MiB /  8118MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce ...  Off  | 00000000:05:00.0 Off |                  N/A |
| 62%   73C    P2   122W / 180W |   4923MiB /  8119MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

echo $LD_LIBRARY_PATH 
/usr/local/cuda-10.1/lib64

**Comment by longqua69** [comment]
Hope the Tensorflow team can help with this soon.

**Comment by sulc** [comment]
I am facing **the same issue**.

I tried blindly following a [similar issue from tensorflow/text](https://github.com/tensorflow/text/issues/385) where tensorflow:2.3.0 worked, and
- changed `research/object_detection/dockerfiles/tf2/Dockerfile`  to `tensorflow/tensorflow:2.3.0-gpu`
- re-build the docker with `--no-cache`
- re-run protoc (after removing the previous output)
- re-installed with pip using `--no-cache-dir`

… but with no luck, I am still getting the same error :-(

**Comment by sulc** [comment]
What (so far) seems to work for me as a workaround without gcloud and gsutil:
- change `tensorflow/tensorflow:2.2.0-gpu` to `tensorflow/tensorflow:2.7.0-gpu` on line 1 in [tf2/Dockerfile](https://github.com/tensorflow/models/blob/master/research/object_detection/dockerfiles/tf2/Dockerfile)
- comment out installation of gcloud and gsutil on lines 18-21 (otherwise it fails with this image..)

**Comment by yalcina** [comment]
@sulc It worked for me, thanks.

**Comment by jacoverster** [comment]
Also worked for me. Thanks @sulc

**Comment by pindinagesh** [comment]
Hi @longqua69 

Could you please try with the latest TF version with compatible python version and you can refer this [test build](https://www.tensorflow.org/install/source_windows#tested_build_configurations), let us know if this issue still persists. Thank you!

**Comment by vitorbds** [comment]
Any update ?
