### ISSUE TITLE
GPU memory error with train.py and eval.py running together

### ISSUE THREAD

**Issue by aloerch** [tensorflow/models#1854]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: not yet...
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 18
- **TensorFlow installed from (source or binary)**: pip tensorflow-gpu
- **TensorFlow version (use command below)**: ('v1.2.0-rc2-21-g12f033d', '1.2.0')
- **CUDA/cuDNN version**: Cuda compilation tools, release 8.0, V8.0.44
- **GPU model and memory**: eVGA GTX 1080Ti, 11Gb
- **Exact command to reproduce**:
Run 1st in one terminal:

```
python object_detection/train.py \
    --logtostderr \
    --pipeline_config_path=/home/meh/.virtualenvs/Project/lib/python2.7/site-packages/tensorflow/models/object_detection/samples/configs/faster_rcnn_resnet101_pets_learn.config \
    --train_dir=/home/meh/.virtualenvs/Project/models/model/train
```
That runs fine, training works... then run in 2nd terminal:

```
python object_detection/eval.py \
    --logtostderr \
    --pipeline_config_path=/home/meh/.virtualenvs/Project/lib/python2.7/site-packages/tensorflow/models/object_detection/samples/configs/faster_rcnn_resnet101_pets_learn.config \
    --checkpoint_dir=/home/meh/.virtualenvs/Project/models/model/train \
    --eval_dir=/home/meh/.virtualenvs/Project/models/model/eval
```
Evaluation fails with an error about the GPU being out of memory (training continues though in the other terminal window with no problem). Here is the traceback:

```
tensorflow/models $ python object_detection/eval.py \
>     --logtostderr \
>     --pipeline_config_path=/home/meh/.virtualenvs/Project/lib/python2.7/site-packages/tensorflow/models/object_detection/samples/configs/faster_rcnn_resnet101_pets_learn.config \
>     --checkpoint_dir=/home/meh/.virtualenvs/Project//models/model/train \
>     --eval_dir=/home/meh/.virtualenvs/Project//models/model/eval
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
INFO:tensorflow:Scale of 0 disables regularizer.
2017-07-04 13:05:20.813917: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-04 13:05:20.813976: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-04 13:05:20.813987: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-04 13:05:20.813995: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-04 13:05:20.814005: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-04 13:05:21.414540: E tensorflow/core/common_runtime/direct_session.cc:138] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 11713708032
Traceback (most recent call last):
  File "object_detection/eval.py", line 161, in <module>
    tf.app.run()
  File "/home/meh/.virtualenvs/Project/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "object_detection/eval.py", line 157, in main
    FLAGS.checkpoint_dir, FLAGS.eval_dir)
  File "/home/meh/.virtualenvs/Project/lib/python2.7/site-packages/tensorflow/models/object_detection/evaluator.py", line 211, in evaluate
    save_graph_dir=(eval_dir if eval_config.save_graph else ''))
  File "/home/meh/.virtualenvs/Project/lib/python2.7/site-packages/tensorflow/models/object_detection/eval_util.py", line 515, in repeated_checkpoint_run
    keys_to_exclude_from_results)
  File "/home/meh/.virtualenvs/Project/lib/python2.7/site-packages/tensorflow/models/object_detection/eval_util.py", line 359, in run_checkpoint_once
    sess = tf.Session(master, graph=tf.get_default_graph())
  File "/home/meh/.virtualenvs/Project/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1292, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/meh/.virtualenvs/Project/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 562, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/meh/.virtualenvs/Project/local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Failed to create session.
```

Based on: 

> Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 11713708032

 it looks like eval.py appears to be trying to run the evaluation on the same GPU that is actively doing the training. I have a 2nd GPU, an eVGA GTX 1080 FTW with 8Gb of RAM that I would be happy to run the eval.py on, and generally speaking, I know how to write my own tensorflow graph using tf.device('/gpu:1') but... I cannot figure out where to insert this in the object_detection code.

I would recommend adding the ability to select the GPU to use for both training and evaluation, possibly as a flag. In the meantime, any help you can offer regarding where I can insert that in the eval.py tree would be much appreciated.

**Comment by schechtman** [comment]
a workaround would be to add after in the trainer.py file add: 

`session_config.gpu_options.per_process_gpu_memory_fraction = 0.8`
(or any fraction that you want and that so that 1 - fraction would be sufficient for your eval.py to run)
after the line : 
```
    session_config = tf.ConfigProto(allow_soft_placement=True                                 
                                                 log_device_placement=False)
```

**Comment by drpngx** [comment]
Yes, you can use `CUDA_VISIBILE_DEVICES` or the [`gpu_options`](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto#L57) to select what you have access to.

**Comment by cy89** [comment]
@aloerch does that work for you?

**Comment by aloerch** [comment]
I will be trying @drpngx's solution tonight and let you know. @schectman's solution would only be ideal to me if I were limited to 1 GPU, but I have 2. 

Cheers!

**Comment by aloerch** [comment]
Ok, so I do not know how to add commits or pull requests or submit my suggested changes to the code on github, but here's what I've worked out: As currently coded, object detection's eval process will fail to run at the same time the train process runs with a GPU out of memory error in some cases. The options are 1) to change the hard-coded fraction of memory used on the GPU for training within the code on a project by project basis, or 2) Make it possible for a user to select a different GPU for the eval process. I've confirmed that my changes listed below work and I would recommend they be added to eval.py in order to improve the usability of object detection.

Add this line to eval.py above import functools:
`import os`

Add this line to eval.py in the flags:
```
flags.DEFINE_string('gpudev','',
                    'Select a GPU Device.')
```

Add this line below FLAGS = flags.FLAGS:
`os.environ["CUDA_VISIBLE_DEVICES"] = 'FLAGS.gpudev'`

Finally, when running eval.py from the terminal, a person could use:
`--gpudev=1`

or some other number (0, 1, 2, etc) to designate the GPU to be used for the process. 

This workaround has resolved my own problem with running the 2 processes simultaneously. Thanks for all of your help!

**Comment by slandersson** [comment]
Hi @aloerch I also have 2 GPUs and have tried what you've done, but I get an error saying it cannot detect the cuda device.

I can run the train and evaluation at 70% - 30% on a single GPU and memory is being allocated across both.

![image](https://user-images.githubusercontent.com/27149279/28035008-eb5f49d6-65aa-11e7-9dfa-037e6e133990.png)

**Comment by aloerch** [comment]
@slandersson I'm not sure why you got the error about it not detecting the cuda device. Maybe you could post the traceback and the lines of code you edited from my recommendation so I can see if I can locate the error? You may have entered a typo or something else could be going on. Also, make sure you check your gpu device number... your first GPU would be GPU 0, the second would be GPU 1, and the third would be GPU 2. This means, if you have 2 GPUs, and you entered --gpudev=2 that would not work because you don't have a third GPU.

Even if the eval process doesn't use much GPU, if you hardcode in a limit of 70/30 for train/eval, your training will be limited to 70%, so that is not a solution I would want to use for myself.

**Comment by thess24** [comment]
I agree there should be support for running eval and train on seperate GPU's.  I think another nice feature would be to set a flag so the GPU can allow for growth rather than using all the memory at the start.

Because I'm working with a single GPU, I've modified the session_config in trainer.py so train.py doesn't automatically consume all the GPU memory:
```
session_config.gpu_options.allow_growth=True

```
After I let this run for a while, I'll start up the eval.py script which seems to be working, but there is certainly a better way to do this. Possibly both the evaluation and training jobs can have flags to allow for growth so this would automatically work on a single GPU.

**Comment by aloerch** [comment]
@thess24 that might be a good feature request. It would be easy to do... my modifications for fixing the GPU out of memory error took a very small amount of time. It would take longer for me to learn how to create pull requests than to implement something like that haha. 

@slandersson did my feedback help with your issue?

**Comment by slandersson** [comment]
@aloerch 

Proof of the gpu device numbers:
```

$ ./deviceQuery -noprompt | egrep "^Device"
Device 0: "GRID K2"
Device 1: "GRID K2"
```

The error I get after implementing the flag:
```
$ python object_detection/eval.py --logtostderr --pipeline_config_path=object_detection/2k_cons/models/model/ssd_inception_v2_pets.config --checkpoint_dir=object_detection/2k_cons/models/model/train --eval_dir=object_detection/2k_cons/models/model/eval --gpudev=1
2017-08-01 13:53:10.784263: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-01 13:53:10.784301: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-01 13:53:10.784409: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-08-01 13:53:10.789162: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE

```

**Comment by aloerch** [comment]
@slandersson 
Did you try it successfully without the quotes around FLAGS.gpudev? My current python version is 2.7 and worked with the quotes...

**Comment by slandersson** [comment]
@aloerch yep confirm it works without the quotes. Python 2.7 too

**Comment by pkdogcom** [comment]
@michaelisard Any updates on this issue?

**Comment by michaelisard** [comment]
@tombstone ?

**Comment by pkdogcom** [comment]
@aloerch @slandersson I also have to remove the quotes to make it work. Otherwise, it would keep throwing CUDA_ERROR_NO_DEVICE error and end up using CPU.

**Comment by aloerch** [comment]
Can someone with edit access to these comments please update my solution by removing g he single quotes around FLAGS.gpudev as suggested by @slandersson? 

Also, @tombstone this is low-hanginf fruit for a pull-request :) I'd be happy to provide additional contributions in the future too.

**Comment by Abduoit** [comment]
Hi @thess24 
I want to run `train.py` and `eval.py` at the same time. I am using single GPU with 8 GB memory. 

Would you please tell me how to do this ? do u mean modify the line number `275` in file `trainer.py `. what about `eval.py` 

Thanks

**Comment by s5plus1** [comment]
Train on a single GPU and eval on CPU: 

- Training: Allow growth

 In trainer.py, add 

`session_config.gpu_options.allow_growth = True` 

behind

`session_config = tf.ConfigProto(allow_soft_placement=True,
                                                    log_device_placement=False)`

- Evaluation: Use CPU

In eval.py, add

`import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'`

**Comment by madekwe** [comment]
I can not train and eval on the same GPU I try to tune gpu memory fraction (in trainer.py) : 

    session_config.gpu_options.per_process_gpu_memory_fraction = 0.4

But tensorflow still allocate all the memory of my GPU (11gb). 
Where should I write :     
session_config.gpu_options.per_process_gpu_memory_fraction = 0.2

? Thanks

**Comment by zeynali** [comment]
@s5plus1,I follow you command , i open 2 terminal windows separately, in ones i run train.py this is ok and running well, but when i run eval.py in the other terminal windows , i got this error:
python3 eval.py \
>         --logtostderr \
>         --checkpoint_dir=training_ssd_mobile_caltech \
>         --eval_dir=eval_caltech \
>         --pipeline_config_path=ssd_mobilenet_v1_coco_2017_11_17/ssd_mobilenet_v1_focal_loss_coco.config 
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
INFO:tensorflow:depth of additional conv before box predictor: 0
2018-02-28 19:37:41.333605: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-02-28 19:37:41.336325: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-02-28 19:37:41.336370: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: mm
2018-02-28 19:37:41.336378: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: mm
2018-02-28 19:37:41.336415: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.111.0
2018-02-28 19:37:41.336437: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.111  Tue Dec 19 23:51:45 PST 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 
"""
2018-02-28 19:37:41.336452: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 384.111.0
2018-02-28 19:37:41.336460: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 384.111.0
INFO:tensorflow:Restoring parameters from training_ssd_mobile_caltech/model.ckpt-0
INFO:tensorflow:Restoring parameters from training_ssd_mobile_caltech/model.ckpt-0
WARNING:root:image 0 does not have groundtruth difficult flag specified
WARNING:root:image 1000 does not have groundtruth difficult flag specified
WARNING:root:image 2000 does not have groundtruth difficult flag specified
[......]

**Comment by aloerch** [comment]
@zeynali following @s5plus1 's solution disables cuda devices from being found by eval.py and therefore you see a message about no cuda devices available. Does the eval keep running? It should have used CPU and kept running for the eval process.

**Comment by zeynali** [comment]
@s5plus1 , i follow your command, you mention Evaluation: Use CPU , therefor , Should not it use cpu? 
It should not be run in GPU ? Right?

**Comment by zeynali** [comment]
@s5plus1 , i follow your command, you mention Evaluation: Use CPU , therefor , Should not it use cpu? 
It should not be run in GPU ? Right?

**Comment by s5plus1** [comment]
@zeynali It seems that the cuda devices were not disabled correctly, and you were using GPU instead of CPU which doesn't make sense if you followed my code:

`import os`
`os.environ['CUDA_VISIBLE_DEVICES'] = '-1'`

**Comment by zeynali** [comment]
s5plus1, Yes ,I did the same. What seems to me: os.environ['CUDA_VISIBLE_DEVICES'] = '-1' didn't work for me , i have TF 1.5 , CUDA8 , CUDNN7 , perhaps i must change '-1' to other. What do you think ?

**Comment by s5plus1** [comment]
@zeynali 
Yes, you can change it if you have multiple GPUs. 

‘-1’ means CPU,
‘0’ means GPU 0,
‘1’ means GPU 1,
etc.

Or you can try another way:
config = tf.ConfigProto(
        device_count = {'GPU': 0}
    )
sess = tf.Session(config=config)

According to https://groups.google.com/a/tensorflow.org/forum/m/#!topic/discuss/cFsmoeO9Nd4

**Comment by zeynali** [comment]
@s5plus1 , where i add this lines ? 
config = tf.ConfigProto(
device_count = {'GPU': 0}
)
sess = tf.Session(config=config)

**Comment by frostell** [comment]
A simple (but effective) way of preventing the eval job or tensorboard from crashing the training is to create a minimal [virtual environment](https://www.tensorflow.org/install/install_linux) and installing tensorflow without GPU support in that environment, then simply activate the virtual environment and start the eval job and it will never take up GPU memory...

**Comment by zeynali** [comment]
@frostell , Have you tried it yourself?

**Comment by frostell** [comment]
yes, of course! this is how I'm always running my models... do you need more specific instructions?

**Comment by frostell** [comment]
(As I understand it, the virtual environment is like an isolated part of your OS where everything from locale to PATH variables can be set in a separate way. It also contains a python and tensorflow installation which is separate from the one you're using in your OS. This is good because you can tweak things without it effecting other python environments. I've actually put my tensorflow-GPU installation in a separate virtualenv as well)

**Comment by madhavajay** [comment]
A much easier way to avoid eval from using GPU is just to set the flags before running it and then unset them after e.g. put this in a .sh file.

```
export CUDA_VISIBLE_DEVICES=-1
python ./object_detection/eval.py \
    --logtostderr \
    --pipeline_config_path=${PATH_TO_YOUR_PIPELINE_CONFIG} \
    --checkpoint_dir=${PATH_TO_TRAIN_DIR} \
    --eval_dir=${PATH_TO_EVAL_DIR}
unset CUDA_VISIBLE_DEVICES
```

**Comment by joydeepmedhi** [comment]
@slandersson Did your 70-30 method work? My training takes all the memory available in gpu! Any work around?

**Comment by joydeepmedhi** [comment]
@madhavajay have you tried fractional GPU training?

**Comment by jvishnuvardhan** [comment]
Automatically closing this out since I understand it to be resolved, but please let me know if I'm mistaken. Please open a new issue if there are any unresolved issues. Thanks!

**Comment by madhavajay** [comment]
You can also disable directly in python or jupyter by placing this in the cells before you load TensorFlow. This works great if you have notebooks or code that you want to run while your also trying to train models etc.

```
# disable GPU so TensorFlow doesnt allocate the whole GPU memory to this notebook
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
```
