### ISSUE TITLE
ptb_word_lm.py  AttributeError: 'module' object has no attribute 'RNNParamsSaveable'

### ISSUE THREAD

**Issue by larryfu** [tensorflow/models#2709]
when running   ptb_word_lm.py  with  tf-nightly 1.5.0-dev20171103
I got this error 

    2017-11-04 16:48:59.759628: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] Creating     TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0, compute capability: 6.1)
	2017-11-04 16:48:59.761131: E tensorflow/stream_executor/cuda/cuda_driver.cc:936] failed to allocate 221.62M (232390656 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
	WARNING:tensorflow:From /home/larry/workspace/tensorflow/models/tutorials/rnn/ptb/ptb_word_lm.py:165: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
	Instructions for updating:
	Please switch to tf.train.get_or_create_global_step
	Traceback (most recent call last):
	  File "/home/larry/workspace/tensorflow/models/tutorials/rnn/ptb/ptb_word_lm.py", line 527, in <module>
	    tf.app.run()
	  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
	    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
	  File "/home/larry/workspace/tensorflow/models/tutorials/rnn/ptb/ptb_word_lm.py", line 502, in main
	    model.import_ops()
	  File "/home/larry/workspace/tensorflow/models/tutorials/rnn/ptb/ptb_word_lm.py", line 272, in import_ops
	    params_saveable = tf.contrib.cudnn_rnn.RNNParamsSaveable(
	AttributeError: 'module' object has no attribute 'RNNParamsSaveable'

It seems that there is no RNNParamsSaveable in cudnn_rnn 
Any idea how to fix it?

**Comment by angersson** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by rkuo2000** [comment]
Same problem here,  (tensorflow 1.4.0 with python 3.6.3 with 1 GPU w CuDA8+CuDNN6.0, Windows 7.0)
$git clone https://github.com/tensorflow/models
$cd ~/models/tutorials/rnn/ptb
(download & unzip simple-samples.tar.gz)
$python ptb_word_lm.py --data_path=./simple-samples/data --model=small 
Error message as below:
Traceback (most recent call last):
  File "ptb_word_lm.py", line 526, in <module>
    tf.app.run()
  File "C:\Python36\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 502, in main
    model.import_ops()
  File "ptb_word_lm.py", line 272, in import_ops
    params_saveable = tf.contrib.cudnn_rnn.RNNParamsSaveable(
AttributeError: module 'tensorflow.contrib.cudnn_rnn' has no attribute 'RNNParamsSaveable'

**Comment by earlofyor714** [comment]
Same problem here, (tensorflow 1.4.0 with python 3.5.4 with 1 GPU w CuDA8+CUDNN6.0, Windows 10)

~/models/tutorials/rnn/ptb (master)
$ python ptb_word_lm.py --data_path=../../../simple-examples/data/ --model=small

Error messages as below:
WARNING:tensorflow:From ptb_word_lm.py:165: get_or_create_global_step (from tens             orflow.contrib.framework.python.ops.variables) is deprecated and will be removed              in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
Traceback (most recent call last):
  File "ptb_word_lm.py", line 525, in <module>
    tf.app.run()
  File "C:\Users\Enkimesh\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensor             flow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 501, in main
    model.import_ops()
  File "ptb_word_lm.py", line 271, in import_ops
    params_saveable = tf.contrib.cudnn_rnn.RNNParamsSaveable(
AttributeError: module 'tensorflow.contrib.cudnn_rnn' has no attribute 'RNNParamsSaveable'

**Comment by angersson** [comment]
https://github.com/tensorflow/tensorflow/commit/b30ce471420384b931ba40fa21ba8838f12a79eb changed RNNParamsSaveable into multiple classes, and ptb_word_lm hasn't been updated yet. @ebrevdo, can you take a look?

**Comment by David-Levinthal** [comment]
can somebody offer a suggestion on how to change the following block from ptb_word_lm.py  (or should this just be commented out). It would be interesting to compare the cuda9/cudnn7 r 1.4 build with the older R1.3 cuda8/cudnn6 buiild
      rnn_params = tf.get_collection_ref("rnn_params")
      if self._cell and rnn_params:
        params_saveable = tf.contrib.cudnn_rnn.RNNParamsSaveable(
            self._cell,
            self._cell.params_to_canonical,
            self._cell.canonical_to_params,
            rnn_params,
            base_variable_scope="Model/RNN")
        tf.add_to_collection(tf.GraphKeys.SAVEABLE_OBJECTS, params_saveable)

**Comment by David-Levinthal** [comment]
commenting out the if block and the tf.add_to_collection line will get the code to run

**Comment by withme6696** [comment]
I change the code as follows, then it works:
if self._cell and rnn_params:
    params_saveable = tf.contrib.cudnn_rnn.CudnnLSTMSaveable(
        rnn_params,
        self._cell.num_layers,
        self._cell.num_units,
        self._cell.input_size,
        self._cell.input_mode,
        self._cell.direction,
        scope="Model/RNN")
remove this line"tf.add_to_collection(tf.GraphKeys.SAVEABLE_OBJECTS, params_saveable)"

**Comment by saurabhpanwar67412** [comment]
Traceback (most recent call last):
  File "ptb_word_lm.py", line 527, in <module>
    tf.app.run()
  File "C:\Users\saurabh\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "ptb_word_lm.py", line 454, in main
    % (len(gpus), FLAGS.num_gpus))
ValueError: Your machine has only 0 gpus which is less than the requested --num_gpus=1.
 please help me to solve this issue . its kinda urgent . i am trying implementing on cpu version . and here is the code link on tensorflow to which i am trying to execute . " https://www.tensorflow.org/tutorials/recurrent"  . please anyone run the code and tell me the errors to resolve it and send the the outcomes of this `tutorial on saurabhpanwar67412@gmail,com or just tell me the error.

**Comment by David-Levinthal** [comment]
This is a different issue.
I believe you have either built, installed a cuda build of TF. You need one
built for a CPU. Possibly with MKL.

**Comment by ebrevdo** [comment]
Or you just run with the extra command line argument

 --num_gpus=0

?

**Comment by saurabhpanwar67412** [comment]
i can't able to understand anything . whats going on . because i am new here . let me tell you the complete process . i have downloaded and install anaconda and the tensorflow packages to run the recurrent neural network code given on the tensorflow website . and when i execute the code using anaconda tensor flow enviornment and then the output what i got was above . i will resolve it later . can you please execute the code for me . and tell me the outcomes of recurrent neural network using tensorflow .. because i have to submit it to the company where i applied for internship . please help me if anyone could do it !

**Comment by saurabhpanwar67412** [comment]
https://www.tensorflow.org/tutorials/recurrent 
here is the link and we have to  execute the command in "run the code" section.

**Comment by saurabhpanwar67412** [comment]
i can't able to understand anything . whats going on . because i am new here . let me tell you the complete process . i have downloaded and install anaconda and the tensorflow packages to run the recurrent neural network code given on the tensorflow website . and when i execute the code using anaconda tensor flow enviornment and then the output what i got was above . i will resolve it later . can you please execute the code for me . and tell me the outcomes of recurrent neural network using tensorflow .. because i have to submit it to the company where i applied for internship . please help me if anyone could do it !

**Comment by David-Levinthal** [comment]
did you add the --num_gpus=0
flag to the invocation?
you are getting the most recent version of PTB, thus you will also have to
do the edits to the code specified by withme6696 near the top of this bug
report to get it to run.
I did what he said and it works
and I suspect you need to be using TF R1.4 to have the new APIs that are
invoked


On Sat, Dec 9, 2017 at 1:04 AM, saurabhpanwar67412 <notifications@github.com

**Comment by saurabhpanwar67412** [comment]
ok .  Thank you so much ! but i can't able to still resolve it  . i will resolve it later . could you please execute the code for me . and tell me the outcomes of recurrent neural network using tensorflow .. because i have to submit it to the company where i applied for internship . please help me if you could do it ! this internship really matters for me and last chance to get internship for next 6 months . i need to submit the outcome only . 
https://www.tensorflow.org/tutorials/recurrent
here is the link and we have to execute the command in "run the code" section.

**Comment by David-Levinthal** [comment]
you have to figure this out.

**Comment by shiningliang** [comment]
@withme6696  Hi, I follow you code. But what should I do with "params_saveable" next? Could you tell the details?

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
