### ISSUE TITLE
Check failed: stream->parent()->GetConvolveAlgorithms

### ISSUE THREAD

**Issue by JesperChristensen89** [tensorflow/models#3226]
I am trying to run [Faster R-CNN Inception V2](http://download.tensorflow.org/models/object_detection/faster_rcnn_inception_v2_coco_2017_11_08.tar.gz) on a Jetson TX2 (Tegra GPU). 

The problem does not seem to arise from memory errors (which is the case running a larger model). The output from the resource monitor states:
```
RAM 6469/7851MB (lfb 5x4MB) cpu [51%@1981,off,off,8%@1980,56%@1980,100%@1983] EMC 2%@1600 APE 150 GR3D 0%@114
RAM 6471/7851MB (lfb 5x4MB) cpu [54%@2035,off,off,8%@2034,50%@2034,100%@2035] EMC 2%@1600 APE 150 GR3D 0%@114
RAM 6475/7851MB (lfb 5x4MB) cpu [9%@2049,off,off,10%@2034,100%@2035,100%@2033] EMC 2%@1600 APE 150 GR3D 0%@216
RAM 6475/7851MB (lfb 5x4MB) cpu [7%@2036,off,off,6%@2034,100%@2035,100%@2036] EMC 2%@1600 APE 150 GR3D 26%@114
RAM 6475/7851MB (lfb 5x4MB) cpu [5%@1982,off,off,3%@1981,100%@1982,100%@1981] EMC 2%@1600 APE 150 GR3D 0%@114
```

The output from Python states:
```
2018-01-22 08:49:31.074043: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1206] Found device 0 with properties: 
name: NVIDIA Tegra X2 major: 6 minor: 2 memoryClockRate(GHz): 1.3005
pciBusID: 0000:00:00.0
totalMemory: 7.67GiB freeMemory: 3.20GiB
2018-01-22 08:49:31.074101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1300] Adding visible gpu device 0
2018-01-22 08:49:31.756800: I tensorflow/core/common_runtime/gpu/gpu_device.cc:987] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2705 MB memory) -> physical GPU (device: 0, name: NVIDIA Tegra X2, pci bus id: 0000:00:00.0, compute capability: 6.2)
2018-01-22 08:49:55.624323: E tensorflow/stream_executor/cuda/cuda_dnn.cc:385] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2018-01-22 08:49:55.624461: E tensorflow/stream_executor/cuda/cuda_dnn.cc:352] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
2018-01-22 08:49:55.624497: F tensorflow/core/kernels/conv_ops.cc:717] Check failed: stream->parent()->GetConvolveAlgorithms( conv_parameters.ShouldIncludeWinogradNonfusedAlgo<T>(), &algorithms)
```
I am running CUDA 8.0 with cuDNN 6.0 and TensorFlow 1.5 (also tested with 1.3).

**Comment by drpngx** [comment]
@derekjchow WDYT?

**Comment by JesperChristensen89** [comment]
@derekjchow @drpngx I found out this was related to a faulty installation of CUDA and cuDNN. This is now fixed, and I am to an issue posted [here](https://github.com/tensorflow/tensorflow/issues/16187)

**Comment by Parasgr7** [comment]
@JesperChristensen89  Try this to set the fraction of GPU memory to be allocated when using session , it worked for me in solving the same problem in TX2 flashed with JetPack 3.2
with Cuda 9.0
Cudnn 7.0
Tensorflow 1.5

( Experimentally choosing GPU memory to be allocated in percentage that worked in my case is : 0.4)

config = tf.ConfigProto()
config.gpu_options.per_process_gpu_memory_fraction = 0.4 
session = tf.InteractiveSession(config=config)

Let me know if this issue is fixed!

**Comment by msharp9** [comment]
@Parasgr7 I was having the same issue and the config code worked for me.

**Comment by tensorflowbutler** [comment]
Hi There,
 We are checking to see if you still need help on this, as this seems to be considerably old issue. Please update this issue with the latest information, code snippet to reproduce your issue and error you are seeing.
 If we don't hear from you in the next 7 days, this issue will be closed automatically. If you don't need help on this issue any more, please consider closing this.
