### ISSUE TITLE
OOM error after training is successfully running (using NASnet backbone)

### ISSUE THREAD

**Issue by ronykalfarisi** [tensorflow/models#3247]
### System information
- **What is the top-level directory of the model you are using**: object_detection
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: tensorflow.1.4.0.whl
- **TensorFlow version (use command below)**: 1.4.0
- **Bazel version (if compiling from source)**: none
- **CUDA/cuDNN version**: 9.0/7.0 
- **GPU model and memory**: 12 GB NVIDIA Tesla K80, 60 GB RAM
- **Exact command to reproduce**: python3 train.py --logstderr --pipeline_config_path=... --train_dir=...

### Describe the problem
 I have successfully created my own custom dataset and I have successfully trained that dataset using resnet101 and inception-resnet. The problem arise when I tried to switch the backbone using nasnet and I got the following error

    "ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape ..."

So, I did some online trouble shooting and I found one solution on issue #1817 . I followed the instruction by adding the following line of code into nasnet config file

    train_config: {
      batch_size: 1
      batch_queue_capacity: 50
      num_batch_queue_threads: 8
      prefetch_queue_capacity: 10
    ...

I tried the code and it ran well. However, after running around 6000 steps,  I still got the OOM error

    INFO:tensorflow:global step 6348: loss = 2.0393 (3.988 sec/step)
    INFO:tensorflow:Saving checkpoint to path /home/ubuntu/crack-detection/structure-crack/models/faster_rcnn_nas_coco_2017_11_08/train/model.ckpt
    INFO:tensorflow:global step 6349: loss = 0.9803 (3.980 sec/step)
    2018-01-25 05:51:25.959402: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 79.73MiB.  Current allocation summary follows.
    ...

    ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[64,17,17,4032]
    	 [[Node: MaxPool2D/MaxPool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 1, 1], 
    ...

Is there anything else I could do to run this smoothly without any OOM errors? Thanks for your help

**EDIT**: The errors show up more frequently now, it'll show after 1000-1500 steps.

**Comment by tatatodd** [comment]
@derekjchow any memory-reducing suggestions here?

**Comment by tahouse** [comment]
@ronykalfarisi Can you share what your solution was? I'm hitting a similar issue on a 1080 Ti. After adding to pipeline config ```second_stage_batch_size: 25```, it works but still getting a concerning error at initialization.

**Comment by ronykalfarisi** [comment]
@tahouse I modified the train_config like I described above and it ran well. If it fails after it run several steps, you just have to re-run it again. Basically, you want to monitor the process once in a while. Hope this helps.

**Comment by tahouse** [comment]
@ronykalfarisi Got it, that's what I've done, but wasn't sure if you had discovered anything else since your last post. I'm up and running now using your solution. Thanks for the quick response!

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if the issue still persists. Thanks!
