### ISSUE TITLE
Tensorflow hangs when starting queues

### ISSUE THREAD

**Issue by Bidski** [tensorflow/models#3386]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes, dataset generation code (converting dataset in tfRecord format using the sample script)
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Mint 18.2 (based on Ubuntu 16.04)
- **TensorFlow installed from (source or binary)**: Source (latest master)
- **TensorFlow version (use command below)**: v1.5.0-2593-gb2a0f1c 1.6.0-rc0
- **Bazel version (if compiling from source)**: 0.10.0
- **CUDA/cuDNN version**: CUDA 9.1, cuDNN 7
- **GPU model and memory**: NVIDIA GTX1080Ti 11GB
- **Exact command to reproduce**: `python3 object_detection/train.py --logtostderr --pipeline_config_path=/media/bidski/Portable/Annotated/tf_objapi/models/ssd_mobilenet/pipeline.pbtxt --train_dir=/media/bidski/Portable/Annotated/tf_objapi/models/ssd_mobilenet/train`

### Describe the problem
When trying to run training in the object detection API (fine-tuning SSD mobilenet), the network is loaded, but training hangs indefinitely. This happens both when using a GPU and also when not using a GPU

### Source code / logs
GPU version
```
$ cd path/to/object/detection/api/models/research
$ python3 object_detection/train.py --logtostderr --pipeline_config_path=/media/bidski/Portable/Annotated/tf_objapi/models/ssd_mobilenet/pipeline.pbtxt --train_dir=/media/bidski/Portable/Annotated/tf_objapi/models/ssd_mobilenet/train 

*** many warnings about deprecated inspect.getargspec() and fromstring ***
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/learning.py:736: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-02-15 10:16:11.290407: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1331] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:65:00.0
totalMemory: 10.91GiB freeMemory: 6.73GiB
2018-02-15 10:16:11.290433: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1410] Adding visible gpu devices: 0
2018-02-15 10:16:11.519519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-02-15 10:16:11.519548: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 
2018-02-15 10:16:11.519552: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N 
2018-02-15 10:16:11.519664: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1021] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6494 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:65:00.0, compute capability: 6.1)
INFO:tensorflow:Restoring parameters from /media/bidski/Portable/Annotated/tf_objapi/models/pretrained/model.ckpt
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path /media/bidski/Portable/Annotated/tf_objapi/models/ssd_mobilenet/train/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
```

CPU version
```
$ cd path/to/object/detection/api/models/research
$ CUDA_VISIBLE_DEVICES= python3 object_detection/train.py --logtostderr --pipeline_config_path=/media/bidski/Portable/Annotated/tf_objapi/models/ssd_mobilenet/pipeline.pbtxt --train_dir=/media/bidski/Portable/Annotated/tf_objapi/models/ssd_mobilenet/train 

*** many warnings about deprecated inspect.getargspec() and fromstring ***
WARNING:tensorflow:From /usr/local/lib/python3.5/dist-packages/tensorflow/contrib/slim/python/slim/learning.py:736: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2018-02-15 09:33:24.144774: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2018-02-15 09:33:24.144806: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: bidski-alien
2018-02-15 09:33:24.144811: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: bidski-alien
2018-02-15 09:33:24.144835: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 387.34.0
2018-02-15 09:33:24.144852: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 387.34.0
2018-02-15 09:33:24.144856: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 387.34.0
INFO:tensorflow:Restoring parameters from /media/bidski/Portable/Annotated/tf_objapi/models/pretrained/model.ckpt
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Starting Session.
INFO:tensorflow:Saving checkpoint to path /media/bidski/Portable/Annotated/tf_objapi/models/ssd_mobilenet/train/model.ckpt
INFO:tensorflow:Starting Queues.
INFO:tensorflow:global_step/sec: 0
```

Apart from printing `INFO:tensorflow:global_step/sec: 0` and `INFO:tensorflow:Saving checkpoint to path /media/bidski/Portable/Annotated/tf_objapi/models/ssd_mobilenet/train/model.ckpt` more, no other output is generated. I let the training run overnight, eventually `INFO:tensorflow:global_step/sec: 0` stops printing out, but checkpoints continue to be saved.

There appear to be no interesting/concerning messages displayed during the bazel build process.

**Comment by Bidski** [comment]
Further information:
- Tensorflow was also built from source using CUDA 9.0, the same behaviour was seen.
- The pre-built tensorflow (installed via `pip3 install tensorflow-gpu`) exhibited the same behaviour when running with CUDA 9.0 (unable to test with CUDA 9.1 as the prebuilt tensorflow does not support this)

**Comment by cy89** [comment]
@Bidski could you please try backing off to CUDA 8.0?

**Comment by Bidski** [comment]
CUDA 8.0 with tensorflow v1.5.0-2593-gb2a0f1c 1.6.0-rc0 provides the same results.
As does CUDA 8.0 with tensorflow v1.5.0 
cuDNN 7 for both cases.

**Comment by Bidski** [comment]
Ok, I discovered what the problem was.

Turns out that I had an error while generating my TFRecord files and they ended up being empty. I assume that the training script was then just doing nothing, giving the appearance that the tensorflow was hanging.

I think that invalid/empty datasets should be flagged as a warning.

**Comment by mrry** [comment]
We report EOF when you do `dataset.repeat()` and `dataset` is empty, to avoid an infinite loop. I'm not familiar with what the code is here, so can't say how you might detect that the input is invalid. We could warn when e.g. a TFRecordDataset terminates without producing any data, but a general empty dataset isn't something we'd want to warn about (any more than we'd warn about an empty list!).

**Comment by cy89** [comment]
@Bidski I'll close; please feel free to reopen or file a new bug if there's a particular feature request you'd like to file about invalid/empty cases.
