### ISSUE TITLE
Memory size for running adversarial_text

### ISSUE THREAD

**Issue by sungraepark** [tensorflow/models#3865]
I try to run the model for sentiment classification task with adversarial perturbation from (https://github.com/tensorflow/models/tree/master/research/adversarial_text)

In the code, computational time is explained as 1.8 hours or 4 hours on a single GPU (Pascal Titan X, cuDNNv5)
When I try to learn the model with the code, I got ResourceExhaustedError (Out of Memory) on a single GPU (Pascal Titan X, 12G memory)

How much memory does the program need?

If the parameters are changed, the program would work...
But, I don't hope to change the parameters (e.g. batch size)...

is it possible to run the code on a single GPU (Pascal Titan X, 12G memory)?

@rsepassi @a-dai

**Comment by sungraepark** [comment]
I figure out that the code works on Pascal Titan X.  
My problem was the version of the tensorflow and "adversarial_text" for 1.2v
I updated tensorflow to 1.5v and used the new version of "adversarial_text". 
My problem was disappeared.

**Comment by robieta** [comment]
Lovely. Thanks for the update.

**Comment by jhscsc** [comment]
@sungraepark Could you run pretraining with batch size of 256 just fine? If so, what was your loss at the end of training? 

I am training on 1x GTX 1080Ti, and when I trained using batch 256, it said I was out of memory, so I had to change it to 128. But now, after training it is stuck at a loss of about 3.3. Is that normal/correct?

Thanks!

**Comment by sungraepark** [comment]
@jhscsc I ran the pretraining code on Tesla P40..  and The last value of the loss was 3.22. I think your loss value is similar to the case of the 256 batch size. :)

**Comment by jhscsc** [comment]
Yep, that's what I had. When I ran other experiments with batch sizes of 32, 64, and 128, they all converged to about 3.2-3.3. Then when I ran adversarial training, it fully reproduced results from the paper. Thank you!
