### ISSUE TITLE
Cannot evaluate the finetuned VGG model using eval_image_classifier.py script from tensorflow/models/research/slim/

### ISSUE THREAD

**Issue by denyoblur** [tensorflow/models#4468]
Hi Tensorflow dev team,

I have an issue when evaluating the VGG_16 model, I use the template provided in the README file and change it into:

```
CODE_DIR=/path/to/tensorflow/models/research/slim
CHECKPOINT_FILE=/path/to/finetuned_models/vgg_16/
DATASET_DIR=./data/
python ${CODE_DIR}/eval_image_classifier.py \
    --alsologtostderr \
    --checkpoint_path=${CHECKPOINT_FILE} \
    --dataset_dir=${DATASET_DIR} \
    --dataset_name=mydataset \
    --dataset_split_name=validation \
    --model_name=vgg_16
```

I ran the script and seem like it cannot evaluate due to the out of GPU memory issue. Actually, I didn't meet any problem when evaluating the ResNet, or Inception model, they're all done successfully.

Here some infos:

- The `mydataset` is generated using the default setting of the `download_and_convert_data.py` script (as the flower dataset in the README.md file)
- This is my GPU: GTX 980 TI 

1. 2816CUDA Cores
2. 1000Base Clock (MHz)
3. 1075Boost Clock (MHz)
4. 176Texture Fill Rate (GigaTexels/sec)

- GPU Memory Specs:

1. 7.0 GbpsMemory Clock
2. 6 GBStandard Memory Config
3. GDDR5Memory Interface
4. 384-bitMemory Interface Width
5. 336.5Memory Bandwidth (GB/sec)

- Here is the error:
```
2018-06-06 13:47:20.678673: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 980 Ti
major: 5 minor: 2 memoryClockRate (GHz) 1.2785
pciBusID 0000:01:00.0
Total memory: 5.93GiB
Free memory: 5.65GiB
2018-06-06 13:47:20.678697: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-06-06 13:47:20.678704: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-06-06 13:47:20.678713: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 980 Ti, pci bus id: 0000:01:00.0)
INFO:tensorflow:Restoring parameters from /home/image-classifier/fine-tune/finetuned_models/vgg_16/model.ckpt-22096
2018-06-06 13:47:25.265031: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.15GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2018-06-06 13:47:35.321397: W tensorflow/core/common_runtime/bfc_allocator.cc:273] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.20GiB.  Current allocation summary follows.
2018-06-06 13:47:35.321430: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (256): 	Total Chunks: 2, Chunks in use: 0 512B allocated for chunks. 2B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321444: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (512): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321455: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (1024): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321468: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (2048): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321483: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (4096): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321497: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (8192): 	Total Chunks: 1, Chunks in use: 0 10.0KiB allocated for chunks. 1B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321510: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (16384): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321524: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (32768): 	Total Chunks: 1, Chunks in use: 0 36.2KiB allocated for chunks. 4B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321537: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (65536): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321549: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (131072): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321563: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (262144): 	Total Chunks: 1, Chunks in use: 0 288.5KiB allocated for chunks. 196.0KiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321577: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (524288): 	Total Chunks: 1, Chunks in use: 0 576.0KiB allocated for chunks. 196.0KiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321589: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (1048576): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321603: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (2097152): 	Total Chunks: 1, Chunks in use: 0 2.25MiB allocated for chunks. 588.0KiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321616: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (4194304): 	Total Chunks: 1, Chunks in use: 0 4.50MiB allocated for chunks. 588.0KiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321630: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (8388608): 	Total Chunks: 1, Chunks in use: 0 11.14MiB allocated for chunks. 7.18MiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321644: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (16777216): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321656: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (33554432): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321668: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (67108864): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321681: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (134217728): 	Total Chunks: 0, Chunks in use: 0 0B allocated for chunks. 0B client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321695: I tensorflow/core/common_runtime/bfc_allocator.cc:643] Bin (268435456): 	Total Chunks: 1, Chunks in use: 0 383.00MiB allocated for chunks. 13.54MiB client-requested for chunks. 0B in use in bin. 0B client-requested in use in bin.
2018-06-06 13:47:35.321708: I tensorflow/core/common_runtime/bfc_allocator.cc:660] Bin for 1.20GiB was 256.00MiB, Chunk State: 
2018-06-06 13:47:35.321721: I tensorflow/core/common_runtime/bfc_allocator.cc:666]   Size: 383.00MiB | Requested Size: 13.54MiB | in_use: 0, prev:   Size: 9.00MiB | Requested Size: 9.00MiB | in_use: 1, next:   Size: 392.00MiB | Requested Size: 392.00MiB | in_use: 1
2018-06-06 13:47:35.321732: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709840000 of size 1280
2018-06-06 13:47:35.321740: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709840500 of size 512
2018-06-06 13:47:35.321748: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709840700 of size 1024
2018-06-06 13:47:35.321756: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709840b00 of size 256
2018-06-06 13:47:35.321764: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709840c00 of size 256
2018-06-06 13:47:35.321771: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709840d00 of size 256
2018-06-06 13:47:35.321779: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709840e00 of size 256
2018-06-06 13:47:35.321787: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709840f00 of size 1024
2018-06-06 13:47:35.321795: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709841300 of size 1024
2018-06-06 13:47:35.321803: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709841700 of size 2816
2018-06-06 13:47:35.321811: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709842200 of size 256
2018-06-06 13:47:35.321819: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709842300 of size 6912
2018-06-06 13:47:35.321827: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709843e00 of size 2048
2018-06-06 13:47:35.321835: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709844600 of size 2048
2018-06-06 13:47:35.321842: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709844e00 of size 2048
2018-06-06 13:47:35.321850: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709845600 of size 2048
2018-06-06 13:47:35.321858: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709845e00 of size 256
2018-06-06 13:47:35.321864: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709845f00 of size 256
2018-06-06 13:47:35.321872: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709846000 of size 256
2018-06-06 13:47:35.321880: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709846100 of size 256
2018-06-06 13:47:35.321888: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709846200 of size 256
2018-06-06 13:47:35.321896: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709846300 of size 256
2018-06-06 13:47:35.321903: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709846400 of size 256
2018-06-06 13:47:35.321911: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709846500 of size 256
2018-06-06 13:47:35.321918: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709846600 of size 2048
2018-06-06 13:47:35.321926: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709846f00 of size 256
2018-06-06 13:47:35.321934: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847000 of size 256
2018-06-06 13:47:35.321942: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847100 of size 256
2018-06-06 13:47:35.321950: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847200 of size 256
2018-06-06 13:47:35.321957: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847300 of size 256
2018-06-06 13:47:35.321964: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847400 of size 256
2018-06-06 13:47:35.321972: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847500 of size 256
2018-06-06 13:47:35.321980: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847600 of size 256
2018-06-06 13:47:35.321988: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847700 of size 256
2018-06-06 13:47:35.321995: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847800 of size 256
2018-06-06 13:47:35.322003: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847900 of size 256
2018-06-06 13:47:35.322010: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847a00 of size 256
2018-06-06 13:47:35.322018: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847c00 of size 256
2018-06-06 13:47:35.322025: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847d00 of size 256
2018-06-06 13:47:35.322033: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847e00 of size 256
2018-06-06 13:47:35.322041: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709847f00 of size 256
2018-06-06 13:47:35.322049: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709848000 of size 256
2018-06-06 13:47:35.322056: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709848100 of size 1024
2018-06-06 13:47:35.322064: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709848500 of size 256
2018-06-06 13:47:35.322071: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x70984ae00 of size 16384
2018-06-06 13:47:35.322079: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709857f00 of size 256
2018-06-06 13:47:35.322087: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709858000 of size 256
2018-06-06 13:47:35.322095: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709858100 of size 147456
2018-06-06 13:47:35.322103: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x7098c4300 of size 81920
2018-06-06 13:47:35.322111: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x7098d8300 of size 256
2018-06-06 13:47:35.322118: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x7098d8400 of size 256
2018-06-06 13:47:35.322126: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x7098d8500 of size 294912
2018-06-06 13:47:35.322134: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x7099b0500 of size 512
2018-06-06 13:47:35.322142: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x7099b0700 of size 2359296
2018-06-06 13:47:35.322150: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709bf0700 of size 1179648
2018-06-06 13:47:35.322158: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x709f50700 of size 2359296
2018-06-06 13:47:35.322166: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x70a610700 of size 4718592
2018-06-06 13:47:35.322174: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x70aa90700 of size 9437184
2018-06-06 13:47:35.322181: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x70b390700 of size 9437184
2018-06-06 13:47:35.322189: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x70bc90700 of size 9437184
2018-06-06 13:47:35.322197: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x70c590700 of size 9437184
2018-06-06 13:47:35.322205: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x70d9b4700 of size 16384
2018-06-06 13:47:35.322213: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x70d9b8700 of size 147456
2018-06-06 13:47:35.322221: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x70d9dc700 of size 589824
2018-06-06 13:47:35.322228: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x70da6c700 of size 67108864
2018-06-06 13:47:35.322236: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x711a6c700 of size 9437184
2018-06-06 13:47:35.322244: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x72a26c700 of size 411041792
2018-06-06 13:47:35.322252: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x742a6c700 of size 1284505600
2018-06-06 13:47:35.322261: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x78f36c700 of size 1284505600
2018-06-06 13:47:35.322269: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x7dbc6c700 of size 2224961792
2018-06-06 13:47:35.322277: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x709846e00 of size 256
2018-06-06 13:47:35.322285: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x709847b00 of size 256
2018-06-06 13:47:35.322292: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x709848600 of size 10240
2018-06-06 13:47:35.322300: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x70984ee00 of size 37120
2018-06-06 13:47:35.322308: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x70987c100 of size 295424
2018-06-06 13:47:35.322316: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x709920500 of size 589824
2018-06-06 13:47:35.322324: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x709d10700 of size 2359296
2018-06-06 13:47:35.322331: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x70a190700 of size 4718592
2018-06-06 13:47:35.322339: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x70ce90700 of size 11681792
2018-06-06 13:47:35.322347: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x71236c700 of size 401604608
2018-06-06 13:47:35.322354: I tensorflow/core/common_runtime/bfc_allocator.cc:693]      Summary of in-use Chunks by size: 
2018-06-06 13:47:35.322364: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 35 Chunks of size 256 totalling 8.8KiB
2018-06-06 13:47:35.322373: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 512 totalling 1.0KiB
2018-06-06 13:47:35.322381: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 1024 totalling 4.0KiB
2018-06-06 13:47:35.322390: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1280 totalling 1.2KiB
2018-06-06 13:47:35.322399: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 5 Chunks of size 2048 totalling 10.0KiB
2018-06-06 13:47:35.322407: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 2816 totalling 2.8KiB
2018-06-06 13:47:35.322416: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 6912 totalling 6.8KiB
2018-06-06 13:47:35.322425: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 16384 totalling 32.0KiB
2018-06-06 13:47:35.322433: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 81920 totalling 80.0KiB
2018-06-06 13:47:35.322442: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 147456 totalling 288.0KiB
2018-06-06 13:47:35.322451: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 294912 totalling 288.0KiB
2018-06-06 13:47:35.322460: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 589824 totalling 576.0KiB
2018-06-06 13:47:35.322468: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1179648 totalling 1.12MiB
2018-06-06 13:47:35.322477: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 2359296 totalling 4.50MiB
2018-06-06 13:47:35.322485: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 4718592 totalling 4.50MiB
2018-06-06 13:47:35.322493: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 5 Chunks of size 9437184 totalling 45.00MiB
2018-06-06 13:47:35.322502: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 67108864 totalling 64.00MiB
2018-06-06 13:47:35.322511: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 411041792 totalling 392.00MiB
2018-06-06 13:47:35.322520: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 1284505600 totalling 2.39GiB
2018-06-06 13:47:35.322529: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 2224961792 totalling 2.07GiB
2018-06-06 13:47:35.322537: I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 4.96GiB
2018-06-06 13:47:35.322546: I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                  5752553472
InUse:                  5331256064
MaxInUse:               5460263424
NumAllocs:                   13070
MaxAllocSize:           2224961792

2018-06-06 13:47:35.322575: W tensorflow/core/common_runtime/bfc_allocator.cc:277] ***______***************************************************************************xxxxxxxxxxxxxxxx
2018-06-06 13:47:35.322589: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[100,64,224,224]
Traceback (most recent call last):
  File "/home/tensorflow/models/research/slim/eval_image_classifier.py", line 191, in <module>
    tf.app.run()
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/tensorflow/models/research/slim/eval_image_classifier.py", line 187, in main
    variables_to_restore=variables_to_restore)
  File "/home/local/lib/python2.7/site-packages/tensorflow/contrib/slim/python/slim/evaluation.py", line 207, in evaluate_once
    config=session_config)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/training/evaluation.py", line 182, in _evaluate_once
    session.run(eval_ops, feed_dict)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 505, in run
    run_metadata=run_metadata)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 842, in run
    run_metadata=run_metadata)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 952, in run
    run_metadata=run_metadata)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 798, in run
    return self._sess.run(*args, **kwargs)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[100,64,224,224]
	 [[Node: vgg_16/conv1/conv1_2/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](vgg_16/conv1/conv1_1/Relu, vgg_16/conv1/conv1_2/weights/read)]]
	 [[Node: recall/update_op/_797 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_290_recall/update_op", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'vgg_16/conv1/conv1_2/convolution', defined at:
  File "/home/tensorflow/models/research/slim/eval_image_classifier.py", line 191, in <module>
    tf.app.run()
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/tensorflow/models/research/slim/eval_image_classifier.py", line 139, in main
    logits, _ = network_fn(images)
  File "/home/tensorflow/models/research/slim/nets/nets_factory.py", line 141, in network_fn
    return func(images, num_classes, is_training=is_training, **kwargs)
  File "/home/tensorflow/models/research/slim/nets/vgg.py", line 187, in vgg_16
    net = slim.repeat(inputs, 2, slim.conv2d, 64, [3, 3], scope='conv1')
  File "/home/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1780, in repeat
    outputs = layer(outputs, *args, **kwargs)
  File "/home/local/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/home/local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 947, in convolution
    outputs = layer.apply(inputs)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 492, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/layers/convolutional.py", line 158, in call
    data_format=utils.convert_data_format(self.data_format, self.rank + 2))
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 670, in convolution
    op=op)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 662, in op
    name=name)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 131, in _non_atrous_convolution
    name=name)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 399, in conv2d
    data_format=data_format, name=name)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[100,64,224,224]
	 [[Node: vgg_16/conv1/conv1_2/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](vgg_16/conv1/conv1_1/Relu, vgg_16/conv1/conv1_2/weights/read)]]
	 [[Node: recall/update_op/_797 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_290_recall/update_op", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

Is there anyway for me to fit the data with VGG into the memory? Thank you

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by denyoblur** [comment]
I know how to solve this, just add the --batch_size=50 and it works like a charm, thanks
