### ISSUE TITLE
im2txt: model is model.ckpt-1000000; but why is test caption not true

### ISSUE THREAD

**Issue by joytianya** [tensorflow/models#6467]
INFO: Analysed target //im2txt:run_inference (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //im2txt:run_inference up-to-date:
  bazel-bin/im2txt/run_inference
INFO: Elapsed time: 0.085s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO:tensorflow:Building model.
INFO:tensorflow:Initializing vocabulary from file: /data/im2txt/data/mscoco/word_counts.txt
INFO:tensorflow:Created vocabulary with 11520 words
INFO:tensorflow:Running caption generation on 1 files matching /data/im2txt/data/mscoco/raw-data/val2014/COCO_val2014_000000224477.jpg
2019-03-28 15:39:03.360760: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-28 15:39:03.371340: E tensorflow/stream_executor/cuda/cuda_driver.cc:397] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2019-03-28 15:39:03.371391: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: 5d1471fb-a71b-4e4d-8288-55075aee64f4
2019-03-28 15:39:03.371409: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 5d1471fb-a71b-4e4d-8288-55075aee64f4
2019-03-28 15:39:03.371540: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 390.46.0
2019-03-28 15:39:03.371592: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 390.46.0
2019-03-28 15:39:03.371610: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:300] kernel version seems to match DSO: 390.46.0
INFO:tensorflow:Loading model from checkpoint: /data/im2txt/model/train/model.ckpt-1000000
INFO:tensorflow:Restoring parameters from /data/im2txt/model/train/model.ckpt-1000000
INFO:tensorflow:Successfully loaded checkpoint: model.ckpt-1000000
Captions for image COCO_val2014_000000224477.jpg:
  0)  (p=0.000003)
  1) man (p=0.000000)
  2) surfer surfing (p=0.000000)

**Comment by joytianya** [comment]
python3.6.6
centos7.2

**Comment by wfzliuchen** [comment]
the result I got,is also uncorrect.  I don't know why
Captions for image 3.jpg:
  0)  (p=0.000002)
  1) surfer (p=0.000000)
  2) man (p=0.000000)

**Comment by wfzliuchen** [comment]
in im2txt/inference_utils/caption_generator.py , when implementing beam_bearch, there is a bug in this code: 
most_likely_words = np.argsort(word_probabilities)[:-self.beam_size][::-1]

we should change that as following:
most_likely_words = np.argsort(word_probabilities)[-self.beam_size:][::-1]

the result:
![image](https://user-images.githubusercontent.com/15215950/55682403-876ac080-5965-11e9-8cf2-5c6a3f2b8a75.png)

**Comment by joytianya** [comment]
@wfzliuchen you are right . I solve it by your method. and thank you

**Comment by khudebhakti** [comment]
I solved it by using the following:
`most_likely_words = np.argsort(word_probabilities)[::-self.beam_size][::-1]`

result:
![result](https://user-images.githubusercontent.com/8778134/56116779-4f2a3a00-5f84-11e9-9874-6b4c79338d3e.jpg)

**Comment by ymodak** [comment]
Closing this issue since its resolved. Feel free to reopen if have any further problems. Thanks!

**Comment by joytianya** [comment]
@khudebhakti You just turn over the list and take the value of the BEAM Size, it is not accurate enough.
