### ISSUE TITLE
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.

### ISSUE THREAD

**Issue by alon1samuel** [tensorflow/models#7088]
I'm using tensorflow models - slim. 
I've tried to operate the basic tutorial but it makes an error of - 

(0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV2/Conv/Conv2D (defined at tmp/tmp6r0orow2.py:12) ]]
	 [[zero_fraction_66/counts_to_fraction/truediv/_723]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV2/Conv/Conv2D (defined at tmp/tmp6r0orow2.py:12) ]]

When I did the same basic installation on tf 1.12 it worked. Hope this bug is going to be fixed.

------------------------

### System information
- Top-level directory of the model: Tensorflow/models/research/slim
- I've written some code before: Yes
- OS platform : Ubuntu 18.04.2
- Tensorflow 1.14 (from pip install)
- Bazel version : N/A
- Cuda 10/Cudnn 7.4.2
- GPU - Geforce RTX 2070
- Command for recreate error:    python train_image_classifier.py 
--train_dir=${TRAIN_DIR} 
--dataset_name=flowers 
--dataset_split_name=train 
--dataset_dir=${DATASET_DIR} 
--model_name=mobilenet_v2

### Problem
I want to work on tensorflow models slim in my computer.

### Source code / logs
https://github.com/tensorflow/models/tree/master/research/slim#training-a-model-from-scratch 

/media/alon/hdd/models/venv/bin/python /media/alon/hdd/models/research/slim/train_image_classifier.py --train_dir=/media/alon/hdd/models/slim_work/training_output/flowers --dataset_name=flowers --dataset_split_name=train --dataset_dir=/media/alon/hdd/models/slim_work/data/flowers --model_name=mobilenet_v2
WARNING: Logging before flag parsing goes to stderr.
W0623 19:34:14.337526 140302909986624 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0623 19:34:14.339967 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/nets/inception_resnet_v2.py:373: The name tf.GraphKeys is deprecated. Please use tf.compat.v1.GraphKeys instead.

W0623 19:34:14.344032 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:397: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

W0623 19:34:14.346436 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/train_image_classifier.py:590: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0623 19:34:14.346753 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/train_image_classifier.py:399: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0623 19:34:14.346820 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/train_image_classifier.py:399: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0623 19:34:14.347333 140302909986624 deprecation.py:323] From /media/alon/hdd/models/research/slim/train_image_classifier.py:413: create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.create_global_step
W0623 19:34:14.350667 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/datasets/flowers.py:73: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

W0623 19:34:14.351403 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/datasets/dataset_utils.py:127: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

W0623 19:34:14.351555 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/datasets/dataset_utils.py:141: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

W0623 19:34:14.353779 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py:246: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0623 19:34:14.357120 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0623 19:34:14.357654 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:190: limit_epochs (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
W0623 19:34:14.359095 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:199: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0623 19:34:14.359975 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/input.py:199: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
W0623 19:34:14.367116 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/data/parallel_reader.py:95: TFRecordReader.__init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TFRecordDataset`.
W0623 19:34:14.435657 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/preprocessing/inception_preprocessing.py:198: The name tf.summary.image is deprecated. Please use tf.compat.v1.summary.image instead.

W0623 19:34:14.437081 140302909986624 deprecation.py:323] From /media/alon/hdd/models/research/slim/preprocessing/inception_preprocessing.py:148: sample_distorted_bounding_box (from tensorflow.python.ops.image_ops_impl) is deprecated and will be removed in a future version.
Instructions for updating:
`seed2` arg is deprecated.Use sample_distorted_bounding_box_v2 instead.
W0623 19:34:14.440571 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/preprocessing/inception_preprocessing.py:38: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0623 19:34:14.443243 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/preprocessing/inception_preprocessing.py:219: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

W0623 19:34:14.469151 140302909986624 deprecation.py:323] From /media/alon/hdd/models/research/slim/train_image_classifier.py:458: batch (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.batch(batch_size)` (or `padded_batch(...)` if `dynamic_pad=True`).
W0623 19:34:14.480346 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/train_image_classifier.py:485: The name tf.get_collection is deprecated. Please use tf.compat.v1.get_collection instead.

W0623 19:34:14.480634 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/deployment/model_deploy.py:191: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0623 19:34:16.211832 140302909986624 deprecation.py:323] From /media/alon/hdd/models/research/slim/train_image_classifier.py:481: softmax_cross_entropy (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.softmax_cross_entropy instead. Note that the order of the logits and labels arguments has been changed.
W0623 19:34:16.212024 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py:373: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

W0623 19:34:16.226262 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py:374: compute_weighted_loss (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.compute_weighted_loss instead.
W0623 19:34:16.232049 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py:152: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
W0623 19:34:16.233304 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py:154: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
W0623 19:34:16.238119 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/losses/python/losses/loss_ops.py:121: add_arg_scope.<locals>.func_with_args (from tensorflow.contrib.losses.python.losses.loss_ops) is deprecated and will be removed after 2016-12-30.
Instructions for updating:
Use tf.losses.add_loss instead.
W0623 19:34:16.238519 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/train_image_classifier.py:497: The name tf.summary.histogram is deprecated. Please use tf.compat.v1.summary.histogram instead.

W0623 19:34:16.239326 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/train_image_classifier.py:498: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

W0623 19:34:17.345861 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/train_image_classifier.py:257: The name tf.train.exponential_decay is deprecated. Please use tf.compat.v1.train.exponential_decay instead.

W0623 19:34:17.349560 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/train_image_classifier.py:318: The name tf.train.RMSPropOptimizer is deprecated. Please use tf.compat.v1.train.RMSPropOptimizer instead.

W0623 19:34:18.114216 140302909986624 deprecation.py:506] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/rmsprop.py:119: calling Ones.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0623 19:34:19.216597 140302909986624 deprecation_wrapper.py:119] From /media/alon/hdd/models/research/slim/train_image_classifier.py:570: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

W0623 19:34:19.806644 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py:742: Supervisor.__init__ (from tensorflow.python.training.supervisor) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.MonitoredTrainingSession
2019-06-23 19:34:20.158780: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-06-23 19:34:20.190476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.725
pciBusID: 0000:17:00.0
2019-06-23 19:34:20.190675: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-06-23 19:34:20.191983: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-06-23 19:34:20.193202: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-06-23 19:34:20.193466: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-06-23 19:34:20.195271: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-06-23 19:34:20.196816: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-06-23 19:34:20.200191: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-06-23 19:34:20.201272: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-06-23 19:34:20.201587: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-06-23 19:34:20.380148: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x6d45bc0 executing computations on platform CUDA. Devices:
2019-06-23 19:34:20.380168: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce RTX 2070, Compute Capability 7.5
2019-06-23 19:34:20.401565: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3500000000 Hz
2019-06-23 19:34:20.402326: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5075e90 executing computations on platform Host. Devices:
2019-06-23 19:34:20.402363: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-06-23 19:34:20.403529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce RTX 2070 major: 7 minor: 5 memoryClockRate(GHz): 1.725
pciBusID: 0000:17:00.0
2019-06-23 19:34:20.403594: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-06-23 19:34:20.403617: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-06-23 19:34:20.403636: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-06-23 19:34:20.403656: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-06-23 19:34:20.403675: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-06-23 19:34:20.403694: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-06-23 19:34:20.403714: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-06-23 19:34:20.405562: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-06-23 19:34:20.405614: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-06-23 19:34:20.407216: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-23 19:34:20.407248: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-06-23 19:34:20.407260: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-06-23 19:34:20.409739: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6650 MB memory) -> physical GPU (device: 0, name: GeForce RTX 2070, pci bus id: 0000:17:00.0, compute capability: 7.5)
W0623 19:34:20.412763 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
I0623 19:34:20.413954 140302909986624 saver.py:1280] Restoring parameters from /media/alon/hdd/models/slim_work/training_output/flowers/model.ckpt-0
2019-06-23 19:34:21.400938: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
W0623 19:34:21.482418 140302909986624 deprecation.py:323] From /media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1066: get_checkpoint_mtimes (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file utilities to get mtimes.
I0623 19:34:21.483802 140302909986624 session_manager.py:500] Running local_init_op.
I0623 19:34:21.692714 140302909986624 session_manager.py:502] Done running local_init_op.
I0623 19:34:24.301936 140302909986624 learning.py:754] Starting Session.
I0623 19:34:24.419769 140296365004544 supervisor.py:1117] Saving checkpoint to path /media/alon/hdd/models/slim_work/training_output/flowers/model.ckpt
I0623 19:34:24.425295 140302909986624 learning.py:768] Starting Queues.
I0623 19:34:26.459811 140296356611840 supervisor.py:1099] global_step/sec: 0
2019-06-23 19:34:29.158663: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-06-23 19:34:30.094252: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-06-23 19:34:30.116640: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
I0623 19:34:30.140380 140296348219136 coordinator.py:219] Error reported to Coordinator: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV2/Conv/Conv2D (defined at tmp/tmp6r0orow2.py:12) ]]
	 [[zero_fraction_66/counts_to_fraction/truediv/_723]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV2/Conv/Conv2D (defined at tmp/tmp6r0orow2.py:12) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node MobilenetV2/Conv/Conv2D:
 MobilenetV2/Conv/weights/read (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:285)	
 MobilenetV2/input (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:365)

Input Source operations connected to node MobilenetV2/Conv/Conv2D:
 MobilenetV2/Conv/weights/read (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:285)	
 MobilenetV2/input (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:365)

Original stack trace for 'MobilenetV2/Conv/Conv2D':
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 487, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "media/alon/hdd/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 470, in clone_fn
    logits, end_points = network_fn(images)
  File "media/alon/hdd/models/research/slim/nets/nets_factory.py", line 155, in network_fn
    **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet_v2.py", line 164, in mobilenet
    **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py", line 366, in mobilenet
    net, end_points = mobilenet_base(inputs, scope=scope, **mobilenet_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py", line 285, in mobilenet_base
    net = opdef.op(net, **params)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1159, in convolution2d
    conv_dims=2)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1479, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 450, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "tmp/tmp6r0orow2.py", line 12, in tf__call
    outputs = ag__.converted_call('_convolution_op', self, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (inputs, self.kernel), None)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 356, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in _call_unconverted
    return f(*args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1079, in __call__
    return self.conv_op(inp, filter)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 635, in __call__
    return self.call(inp, filter)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 234, in __call__
    name=self.name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()
Traceback (most recent call last):
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node MobilenetV2/Conv/Conv2D}}]]
	 [[zero_fraction_66/counts_to_fraction/truediv/_723]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node MobilenetV2/Conv/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 495, in run
    self.run_loop()
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 1045, in run_loop
    [self._sv.summary_op, self._sv.global_step])
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV2/Conv/Conv2D (defined at tmp/tmp6r0orow2.py:12) ]]
	 [[zero_fraction_66/counts_to_fraction/truediv/_723]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV2/Conv/Conv2D (defined at tmp/tmp6r0orow2.py:12) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node MobilenetV2/Conv/Conv2D:
 MobilenetV2/Conv/weights/read (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:285)	
 MobilenetV2/input (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:365)

Input Source operations connected to node MobilenetV2/Conv/Conv2D:
 MobilenetV2/Conv/weights/read (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:285)	
 MobilenetV2/input (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:365)

Original stack trace for 'MobilenetV2/Conv/Conv2D':
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 487, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "media/alon/hdd/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 470, in clone_fn
    logits, end_points = network_fn(images)
  File "media/alon/hdd/models/research/slim/nets/nets_factory.py", line 155, in network_fn
    **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet_v2.py", line 164, in mobilenet
    **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py", line 366, in mobilenet
    net, end_points = mobilenet_base(inputs, scope=scope, **mobilenet_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py", line 285, in mobilenet_base
    net = opdef.op(net, **params)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1159, in convolution2d
    conv_dims=2)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1479, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 450, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "tmp/tmp6r0orow2.py", line 12, in tf__call
    outputs = ag__.converted_call('_convolution_op', self, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (inputs, self.kernel), None)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 356, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in _call_unconverted
    return f(*args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1079, in __call__
    return self.conv_op(inp, filter)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 635, in __call__
    return self.call(inp, filter)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 234, in __call__
    name=self.name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

2019-06-23 19:34:30.142558: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-06-23 19:34:30.153959: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node MobilenetV2/Conv/Conv2D}}]]
	 [[gradients/MobilenetV2/expanded_conv_16/depthwise/BatchNorm/FusedBatchNorm_grad/FusedBatchNormGrad/_1467]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node MobilenetV2/Conv/Conv2D}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 1004, in managed_session
    yield sess
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 775, in train
    train_step_kwargs)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 490, in train_step
    run_metadata=run_metadata)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV2/Conv/Conv2D (defined at tmp/tmp6r0orow2.py:12) ]]
	 [[gradients/MobilenetV2/expanded_conv_16/depthwise/BatchNorm/FusedBatchNorm_grad/FusedBatchNormGrad/_1467]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV2/Conv/Conv2D (defined at tmp/tmp6r0orow2.py:12) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node MobilenetV2/Conv/Conv2D:
 MobilenetV2/Conv/weights/read (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:285)	
 MobilenetV2/input (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:365)

Input Source operations connected to node MobilenetV2/Conv/Conv2D:
 MobilenetV2/Conv/weights/read (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:285)	
 MobilenetV2/input (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:365)

Original stack trace for 'MobilenetV2/Conv/Conv2D':
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 487, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "media/alon/hdd/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 470, in clone_fn
    logits, end_points = network_fn(images)
  File "media/alon/hdd/models/research/slim/nets/nets_factory.py", line 155, in network_fn
    **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet_v2.py", line 164, in mobilenet
    **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py", line 366, in mobilenet
    net, end_points = mobilenet_base(inputs, scope=scope, **mobilenet_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py", line 285, in mobilenet_base
    net = opdef.op(net, **params)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1159, in convolution2d
    conv_dims=2)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1479, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 450, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "tmp/tmp6r0orow2.py", line 12, in tf__call
    outputs = ag__.converted_call('_convolution_op', self, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (inputs, self.kernel), None)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 356, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in _call_unconverted
    return f(*args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1079, in __call__
    return self.conv_op(inp, filter)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 635, in __call__
    return self.call(inp, filter)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 234, in __call__
    name=self.name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/alon/hdd/models/research/slim/train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/media/alon/hdd/models/research/slim/train_image_classifier.py", line 586, in main
    sync_optimizer=optimizer if FLAGS.sync_replicas else None)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/slim/python/slim/learning.py", line 790, in train
    ignore_live_threads=ignore_live_threads)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 1014, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 839, in stop
    ignore_live_threads=ignore_live_threads)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 297, in stop_on_exception
    yield
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/coordinator.py", line 495, in run
    self.run_loop()
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/training/supervisor.py", line 1045, in run_loop
    [self._sv.summary_op, self._sv.global_step])
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run
    run_metadata_ptr)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run
    feed_dict_tensor, options, run_metadata)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run
    run_metadata)
  File "/media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV2/Conv/Conv2D (defined at tmp/tmp6r0orow2.py:12) ]]
	 [[zero_fraction_66/counts_to_fraction/truediv/_723]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node MobilenetV2/Conv/Conv2D (defined at tmp/tmp6r0orow2.py:12) ]]
0 successful operations.
0 derived errors ignored.

Errors may have originated from an input operation.
Input Source operations connected to node MobilenetV2/Conv/Conv2D:
 MobilenetV2/Conv/weights/read (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:285)	
 MobilenetV2/input (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:365)

Input Source operations connected to node MobilenetV2/Conv/Conv2D:
 MobilenetV2/Conv/weights/read (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:285)	
 MobilenetV2/input (defined at media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py:365)

Original stack trace for 'MobilenetV2/Conv/Conv2D':
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 590, in <module>
    tf.app.run()
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 487, in main
    clones = model_deploy.create_clones(deploy_config, clone_fn, [batch_queue])
  File "media/alon/hdd/models/research/slim/deployment/model_deploy.py", line 193, in create_clones
    outputs = model_fn(*args, **kwargs)
  File "media/alon/hdd/models/research/slim/train_image_classifier.py", line 470, in clone_fn
    logits, end_points = network_fn(images)
  File "media/alon/hdd/models/research/slim/nets/nets_factory.py", line 155, in network_fn
    **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet_v2.py", line 164, in mobilenet
    **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py", line 366, in mobilenet
    net, end_points = mobilenet_base(inputs, scope=scope, **mobilenet_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/research/slim/nets/mobilenet/mobilenet.py", line 285, in mobilenet_base
    net = opdef.op(net, **params)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1159, in convolution2d
    conv_dims=2)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1479, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 537, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 146, in wrapper
    ), args, kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 450, in converted_call
    result = converted_f(*effective_args, **kwargs)
  File "tmp/tmp6r0orow2.py", line 12, in tf__call
    outputs = ag__.converted_call('_convolution_op', self, ag__.ConversionOptions(recursive=True, force_conversion=False, optional_features=(), internal_convert_user_code=True), (inputs, self.kernel), None)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 356, in converted_call
    return _call_unconverted(f, args, kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/autograph/impl/api.py", line 255, in _call_unconverted
    return f(*args)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1079, in __call__
    return self.conv_op(inp, filter)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 635, in __call__
    return self.call(inp, filter)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 234, in __call__
    name=self.name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1953, in conv2d
    name=name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1071, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op
    op_def=op_def)
  File "media/alon/hdd/models/venv/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()

Process finished with exit code 1

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by alon1samuel** [comment]
Hi is it ok now?

Thanks.

**Comment by jideee** [comment]
Has the problem been solved？ I am facing the same problem. this is my problem
INFO:tensorflow:Error reported to Coordinator: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node FeatureExtractor/MobilenetV2/Conv/Conv2D (defined at /home/cjd/models/research/nets/mobilenet/mobilenet.py:285) ]]
	 [[node Loss/Cast_36 (defined at /home/cjd/models/research/object_detection/core/losses.py:679) ]]

**Comment by jideee** [comment]
Has the problem been solved？ I am facing the same problem. this is my problem . thank you!
INFO:tensorflow:Error reported to Coordinator: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
[[node FeatureExtractor/MobilenetV2/Conv/Conv2D (defined at /home/cjd/models/research/nets/mobilenet/mobilenet.py:285) ]]
[[node Loss/Cast_36 (defined at /home/cjd/models/research/object_detection/core/losses.py:679) ]]

**Comment by alon1samuel** [comment]
Hi, 
I didn't need it anymore. But I didn't get an answer.

**Comment by thuc248997** [comment]
@alon1samuel  how to fix that bug? I got the same error!!! tks so much!

**Comment by Wo-Ki** [comment]
How to fix that? When I run faster_rcnn_inception_v2, I met the same question. tks so much!

**Comment by ouclbc** [comment]
same issue
(0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D (defined at /disk2/chengjin/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[control_dependency_1/_6257]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node FeatureExtractor/MobilenetV1/MobilenetV1/Conv2d_0/Conv2D (defined at /disk2/chengjin/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

**Comment by jasperlin1996** [comment]
Hi everyone,

I just break into this issue which shows a similar error message.
My experiment environment is listed as below:
* Ubuntu 18.04
* tf 2.3.0 & tf-gpu 2.3.0
* CUDA 10.1
* cuDNN 7.6
* RTX 2080 Super with 8G VRAM

This solution works for me, hope this helps!

```python
# Source: https://davistseng.blogspot.com/2019/11/tensorflow-2.html?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed:+DavisTsengsBlog+(Davis+Tseng%27s+Blog)
# Problem: cuDNN failed to initialize
# Usage: Call `solve_cudnn_error()` at the start of the file

import tensorflow as tf

def solve_cudnn_error():
    gpus = tf.config.experimental.list_physical_devices('GPU')
    if gpus:
        try:
            # Currently, memory growth needs to be the same across GPUs
            for gpu in gpus:
                tf.config.experimental.set_memory_growth(gpu, True)
            logical_gpus = tf.config.experimental.list_logical_devices('GPU')
            print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
        except RuntimeError as e:
            # Memory growth must be set before GPUs have been initialized
            print(e)
```

**Comment by kumariko** [comment]
@alon1samuel We are checking to see if you still need help on this issue? Please have a look on the [link1](https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in) , [link2](https://stackoverflow.com/questions/59873568/unknownerror-failed-to-get-convolution-algorithm) and let us know if it helps? Thanks!

**Comment by alon1samuel** [comment]
Sadly I don't remember about the error anymore as I'm not using Tensorflow slim models. 
Maybe someone else above can comment if the errors still occurs? @kumariko  
I'm fine with closing this, anyway.
Thanks!

**Comment by kumariko** [comment]
@alon1samuel Thanks for the confirmation. Closing this issue for now.
