### ISSUE TITLE
Tensorflow Object Detection API ptax Error with ptax

### ISSUE THREAD

**Issue by NiksanJP** [tensorflow/models#7113]
So I have this code

`import numpy as np
import os
import six.moves.urllib as urllib
import sys
import tarfile
import tensorflow as tf
import zipfile
from collections import defaultdict
from io import StringIO
from matplotlib import pyplot as plt
from PIL import Image
import cv2
cap = cv2.VideoCapture(0)
sys.path.append("..")

from object_detection.utils import label_map_util
from object_detection.utils import visualization_utils as vis_util 

model = 'rfcn_resnet101_coco_2018_01_28'

MODEL_NAME = model
MODEL_FILE = 'D:/Python/' + model

PATH_TO_CKPT = 'D:/Python/' + model + '/frozen_inference_graph.pb'

PATH_TO_LABELS = 'D:/Python/mscoco_label_map.pbtxt'

NUM_CLASSES = 90

detection_graph = tf.Graph()
with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')

with detection_graph.as_default():
  od_graph_def = tf.GraphDef()
  with tf.gfile.GFile(PATH_TO_CKPT, 'rb') as fid:
    serialized_graph = fid.read()
    od_graph_def.ParseFromString(serialized_graph)
    tf.import_graph_def(od_graph_def, name='')
    
label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
categories = label_map_util.convert_label_map_to_categories(label_map, max_num_classes=NUM_CLASSES, use_display_name=True)
category_index = label_map_util.create_category_index(categories)

with detection_graph.as_default():
  with tf.Session(graph=detection_graph) as sess:
    while True:
      ret, image_np = cap.read()
      # Expand dimensions since the model expects images to have shape: [1, None, None, 3]
      image_np_expanded = np.expand_dims(image_np, axis=0)
      image_tensor = detection_graph.get_tensor_by_name('image_tensor:0')
      # Each box represents a part of the image where a particular object was detected.
      boxes = detection_graph.get_tensor_by_name('detection_boxes:0')
      # Each score represent how level of confidence for each of the objects.
      # Score is shown on the result image, together with the class label.
      scores = detection_graph.get_tensor_by_name('detection_scores:0')
      classes = detection_graph.get_tensor_by_name('detection_classes:0')
      num_detections = detection_graph.get_tensor_by_name('num_detections:0')
      # Actual detection.
      (boxes, scores, classes, num_detections) = sess.run(
        [boxes, scores, classes, num_detections],
        feed_dict={image_tensor: image_np_expanded})
      # Visualization of the results of a detection.
      vis_util.visualize_boxes_and_labels_on_image_array(
          image_np,
          np.squeeze(boxes),
          np.squeeze(classes).astype(np.int32),
          np.squeeze(scores),
          category_index,
          use_normalized_coordinates=True,
          line_thickness=8)
      cv2.imshow('object detection', cv2.resize(image_np, (800,600)))
`

I have entered all the folder locations and the name correctly. I 
 get CUDNN_STATUS_INTERNAL_ERROR OR
heaps of 
`2019-06-28 00:04:13.171528: W tensorflow/stream_executor/cuda/redzone_allocator.cc:294] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation
2019-06-28 00:04:13.198421: W tensorflow/stream_executor/cuda/redzone_allocator.cc:294] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation
2019-06-28 00:04:13.207294: W tensorflow/stream_executor/cuda/redzone_allocator.cc:294] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation`

OS: Windows 10
Tensorflow: 2.0.0b and 1.14
CUDA: 10

Need help!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
What is the top-level directory of the model you are using
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Acejoy** [comment]
yes i too have the same the same issue

**System information**
What is the top-level directory of the model you are using:
\models\research\object_detection\

**Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**
NO, trying to use model_main.py

**OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10

**TensorFlow installed from (source or binary):**
installed using pip(pip install tensorflow-gpu)

**TensorFlow version (use command below):**
v2.0.0

**Bazel version (if compiling from source):**
N/A

**CUDA/cuDNN version:**
CUDA Version 10.0.130
cuDNN: 7.6.4

**GPU model and memory:**
GeForce GTX 1050  4 GB dedicated, 3.9 GB shared

**Exact command to reproduce:**
runt the object_detection_tutorial.ipynb file 


**Describe the problem**
and it got stuck at the loop where the image results were meant to be shown i.e.:-

`for image_path in TEST_IMAGE_PATHS:
  show_inference(detection_model, image_path)`

.
It stayed here until the jupyter notebook dispalyed a message saying kernel has died.
When tried to run it in anaconda prompt ,the following  was displayed at the end after which the no images were shown and the process ended.

> W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
Relying on driver to perform ptx compilation. This message will be only logged once.



Please look into this matter.

**Comment by NiksanJP** [comment]
> yes i too have the same the same issue
> 
> **System information**
> What is the top-level directory of the model you are using:
> \models\research\object_detection\
> 
> **Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**
> NO, trying to use model_main.py
> 
> **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
> Windows 10
> 
> **TensorFlow installed from (source or binary):**
> installed using pip(pip install tensorflow-gpu)
> 
> **TensorFlow version (use command below):**
> v2.0.0
> 
> **Bazel version (if compiling from source):**
> N/A
> 
> **CUDA/cuDNN version:**
> CUDA Version 10.0.130
> cuDNN: 7.6.4
> 
> **GPU model and memory:**
> GeForce GTX 1050 4 GB dedicated, 3.9 GB shared
> 
> **Exact command to reproduce:**
> runt the object_detection_tutorial.ipynb file
> 
> **Describe the problem**
> and it got stuck at the loop where the image results were meant to be shown i.e.:-
> 
> `for image_path in TEST_IMAGE_PATHS: show_inference(detection_model, image_path)`
> 
> .
> It stayed here until the jupyter notebook dispalyed a message saying kernel has died.
> When tried to run it in anaconda prompt ,the following was displayed at the end after which the no images were shown and the process ended.
> 
> > W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
> > Relying on driver to perform ptx compilation. This message will be only logged once.
> 
> Please look into this matter.

I have looked into the matter and I decided to re-install everything. It worked

**Comment by Acejoy** [comment]
> > yes i too have the same the same issue
> > **System information**
> > What is the top-level directory of the model you are using:
> > \models\research\object_detection\
> > **Have I written custom code (as opposed to using a stock example script provided in TensorFlow):**
> > NO, trying to use model_main.py
> > **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
> > Windows 10
> > **TensorFlow installed from (source or binary):**
> > installed using pip(pip install tensorflow-gpu)
> > **TensorFlow version (use command below):**
> > v2.0.0
> > **Bazel version (if compiling from source):**
> > N/A
> > **CUDA/cuDNN version:**
> > CUDA Version 10.0.130
> > cuDNN: 7.6.4
> > **GPU model and memory:**
> > GeForce GTX 1050 4 GB dedicated, 3.9 GB shared
> > **Exact command to reproduce:**
> > runt the object_detection_tutorial.ipynb file
> > **Describe the problem**
> > and it got stuck at the loop where the image results were meant to be shown i.e.:-
> > `for image_path in TEST_IMAGE_PATHS: show_inference(detection_model, image_path)`
> > .
> > It stayed here until the jupyter notebook dispalyed a message saying kernel has died.
> > When tried to run it in anaconda prompt ,the following was displayed at the end after which the no images were shown and the process ended.
> > > W tensorflow/stream_executor/cuda/redzone_allocator.cc:312] Internal: Invoking ptxas not supported on Windows
> > > Relying on driver to perform ptx compilation. This message will be only logged once.
> > 
> > 
> > Please look into this matter.
> 
> I have looked into the matter and I decided to re-install everything. It worked
okay so reinstall as in only the tensorflow gpu or entire cuda along with cudnn and tensorflow-gpu ?

**Comment by Keyrainn** [comment]
Hello i've encountered the same problem and yes the problem can be resolve by reinstalling everything

@Acejoy just reinstall the conda environment and just rerun back the object_detection_tutorial.ipynb file

**Comment by HemantGorakshGhuge** [comment]
Issue not solved

**Comment by philipsolomonsee** [comment]
Hi everyone,
I have tried everything :  reinstalled tensorflow-gpu 2.1,2.0,1.15 , including installing cuda toolkit 10.0,10.1 according to their respective cudnn version, THE ERROR still exist.

The only to solve this is DOWNGRADE to tensorflow-gpu 1.14.. It will works

**Comment by michalzielinski913** [comment]
> The only to solve this is DOWNGRADE to tensorflow-gpu 1.14.. It will works
It worked for me too, ty.
